//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryPayment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vedio
    {
        public int VedioId { get; set; }
        public string VedioName { get; set; }
        public string VedioPath { get; set; }
    }
}
